# アプリケーション名
spring.application.name=ana-sale-notifier

# データベース設定（H2メモリDB）
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sale
spring.datasource.password=
spring.h2.console.enabled=true
# ANAのタイムセールURL
ana.timesale.url=https://www.ana.co.jp/ja/jp/domestic/theme/timesale/sv/?dom=1

# Slack通知設定（新規追加）
# ここに取得した https://hooks.slack.com/services/... から始まるURLを貼ります
slack.webhook.url=https://vitalize-talk.slack.com/archives/D09MV0BRCBU